### ISSUE TITLE
Arguments with spaces are not handled

### ISSUE THREAD

**Issue by velvia** [quantifind/Sumac#51]
If you pass an argument with spaces in it, surrounded by quotes (either ' or "), sumac thinks it is another argument.  For example:

```
myCmd --rowKeys GLOBALEVENTID --segmentKey ":string 0"
/usr/bin/java
/usr/local/bin/sbt
expecting argument name beginning with "--", instead got 0
```
This is with sumac 0.3.0.

**Comment by Mortimerp9** [comment]
that should work, I am not sure why it would break. See for instance the test:
https://github.com/quantifind/Sumac/blob/master/core/src/test/scala/com/quantifind/sumac/ArgumentParserTest.scala#L60

**Comment by asteele-quantifind** [comment]
myCmd could be stripping off the double quotes.  It should work if passed straight to the java command.

**Comment by velvia** [comment]
Sorry, this is my bad.  I was not quoting `"$@"` which was stripping stuff off.
