### ISSUE TITLE
Handling of Int, Boolean, etc

### ISSUE THREAD

**Issue by squito** [quantifind/Sumac#54]
hey @ryanlecompte -- opening this so you can tell me more about the problems w/ Int, Boolean, etc.

There are unit tests for this (eg. https://github.com/quantifind/Sumac/blob/master/core/src/test/scala/com/quantifind/sumac/FieldArgsTest.scala#L385)

so it should work!

**Comment by jen0liu** [comment]
Omg, imran! Haven't seen that name in ages!

**Comment by Mortimerp9** [comment]
wow, what's happening here? Is it a secret sumac party?

--
Pierre Andrews, Ph.D.

**Comment by ryanlecompte** [comment]
@squito I just checked again. It looks like it's only needed when you are working with options, e.g. `Option[java.lang.Integer]`. Is that right?

**Comment by squito** [comment]
ahhh right, that makes sense.  Seems like the Scala compiler should be able to do that automatically.  Anyway, probably nothing that we can fix in that case.

And yes @Mortimerp9 @jen0liu you should join the big sumac party :)  I can't believe you watch this repo and saw the comments!  hope you guys are doing well.
